### PR TITLE
Remove bundled binaries and update Operator SDK

### PR DESCRIPTION
**Pull request by barreiro**
followed the guide at https://docs.openshift.com/container-platform/4.12/operators/operator_sdk/golang/osdk-golang-updating-projects.html

### CODE REVIEW

**Comment by jesperpedersen** [comment]
And we need `.gitignore` files - and a `make clean` target

**Comment by barreiro** [comment]
updated `kustumize` and `opm` versions

**Comment by barreiro** [comment]
added github action to run `make build`

**Comment by jesperpedersen** [comment]
```
On branch barreiro-master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   api/v1alpha1/groupversion_info.go
	modified:   api/v1alpha1/zz_generated.deepcopy.go
	modified:   config/crd/bases/hyperfoil.io_horreums.yaml
	modified:   config/rbac/role.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	config/crd/bases/_.yaml
```

So `.gitignore` and a `make clean` target

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Pull request merged**
